### PR TITLE
Fix PS3 Build - Include nfs4 files in compilation.

### PR DESCRIPTION
**Pull request by rhynec**
Compilation failed due to changes introduced in https://github.com/sahlberg/libnfs/commit/cdb377532a814860083ed00a2b1835d0c4f2233a. Compilation is now successful.

### CODE REVIEW

**Comment by sahlberg** [comment]
Merged. Thanks!
