### ISSUE TITLE
FYI: glibc 2.25 - inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated

### ISSUE THREAD

**Issue by MilhouseVH** [sahlberg/libnfs#202]
glibc 2.25 changelog: https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html

```
* The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.
  This means that in a future release, the macros “major”, “minor”, and
  “makedev” will only be available from <sys/sysmacros.h>.

  These macros are not part of POSIX nor XSI, and their names frequently
  collide with user code; see for instance glibc bug 19239 and Red Hat
  bug 130601.  <stdlib.h> includes <sys/types.h> under _GNU_SOURCE, and
  C++ code presently cannot avoid being compiled under _GNU_SOURCE,
  exacerbating the problem.
```
This leads to the following build failure when building against glibc-2.25:
```
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/libnfs-1.11.0/lib/libnfs.c: In function 'specdata3_to_rdev':
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/libnfs-1.11.0/lib/libnfs.c:1765:13: error: In the GNU C Library, "makedev" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "makedev", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "makedev", you should undefine it after including <sys/types.h>. [-Werror]
  return makedev(rdev->specdata1, rdev->specdata2);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                  
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/libnfs-1.11.0/lib/libnfs.c: In function 'nfs_mknod_async':
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/libnfs-1.11.0/lib/libnfs.c:3675:13: error: In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>. [-Werror]
  cb_data->major = major(dev);
             ^~~~~~~~~~~~~~~~~                                                                                                                                                                                       
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.0-devel/libnfs-1.11.0/lib/libnfs.c:3676:13: error: In the GNU C Library, "minor" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "minor", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "minor", you should undefine it after including <sys/types.h>. [-Werror]
  cb_data->minor = minor(dev);
             ^~~~~~~~~~~~~~~~~                                                                                                                                                                                       
```
Since LibreELEC doesn't care about building with older version of glibc this [hack](https://github.com/MilhouseVH/LibreELEC.tv/blob/b0d702ee21d43f342b5db56c5da09d9ed290512b/packages/network/libnfs/patches/libnfs-glibc-2.25.patch) works and allows libnfs to build with glibc-2.25, however I'm sure you can think of something far more elegant and able to support all versions of glibc... :)

**Comment by sahlberg** [comment]
Thanks.

This commit should fix it 5b28ab5d535e0252c05640eef6e280581278dc36

**Comment by MilhouseVH** [comment]
Tested https://github.com/sahlberg/libnfs/commit/5b28ab5d535e0252c05640eef6e280581278dc36 with both glibc-2.24 and glibc-2.25, no more build issues - many thanks!

**Comment by englishb** [comment]
Tested with glibc-2.26, and I encounter this error again, it looks like there was a regression:

```
#include <string>
class MyProjectVersion
{
    unsigned char major() const;
    unsigned char minor() const;
};
```

```
/path/to/file/myversion.h:68:13: error: In the GNU C Library, "major" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "major", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including <sys/types.h>. [-Werror]
     unsigned char major() const;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/file/myversion.h:72:13: error: In the GNU C Library, "minor" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "minor", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "minor", you should undefine it after including <sys/types.h>. [-Werror]
     unsigned char minor() const;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sahlberg** [comment]
myversion.h is not part of libnfs.

Where does this file come from? Maybe you need to include sys/sysmacros.h
to the file that includes this header.

**Comment by englishb** [comment]
Oh, I'm sorry, I thought this was the bug logged against glibc, not libnfs.  Myversion.h was just meant as an example.  I think it is glibc that has a regression here.  In my case, my project is multi-platform and multi-compiler, and only gcc is having this issue.  Including sys/sysmacros.h would not work on other platforms, as this file doesn't exist on most of them.

**Comment by englishb** [comment]
In case anyone else is looking for the corresponding glibc bug, it is here: https://sourceware.org/bugzilla/show_bug.cgi?format=multiple&id=19239
